AllCops:
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'script/**/*'
    - 'db/**/*' # Ignore db folter
    - 'test/test_helper.rb'    # TODO - Autofixer breaking tests
  TargetRubyVersion: 2.1

Metrics/MethodLength:
  Max: 50

Documentation:
  Enabled: false


#Metrics/ClassLength:
#  Max: 350

#Metrics/ModuleLength:
#  Max: 350

#Metrics/AbcSize:
    #  Enabled: false

#Metrics/CyclomaticComplexity:
#  Enabled: false

